version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: order-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafkaesque:
    image: bitnami/kafka:3.4
    container_name: order-kafkaesque
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

#   mysql:
#     image: mysql:8
#     container_name: order-mysql
#     environment:
#       MYSQL_DATABASE: root
#       MYSQL_ROOT_PASSWORD: Root@12345
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   mysql_data:
