spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: Root@12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080
